In [1]:
# Importacion de librerias a utilizar
import os
import pandas as pd
import numpy as np
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns

### ETL Inicial, archivo: **Vehicle Fuel Economy Data.csv**

In [2]:
fuel_economy = pd.read_csv(r'Datasets\Vehicle Fuel Economy Data.csv')
fuel_economy.head()

C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\3167710248.py:1: DtypeWarning: Columns (73,75) have mixed types. Specify dtype option on import or set low_memory=False.
  fuel_economy = pd.read_csv(r'Datasets\Vehicle Fuel Economy Data.csv')

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,2017,BMW,M6 Coupe,17.500588,0.0,0.0,15.0,14.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,09-09-2016,Y,0.0,0.0,0.0
1,2017,BMW,X3 sDrive28i,12.396250,0.0,0.0,21.0,21.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,22-11-2016,Y,0.0,0.0,0.0
2,2016,Infiniti,Q50S Red Sport,13.523182,0.0,0.0,20.0,19.0,0.0,0.0,...,NSX,NaN,0.0,NaN,04-04-2016,26-09-2016,N,0.0,0.0,0.0
3,2017,MINI,John Cooper Works Convertible,11.018889,0.0,0.0,24.0,23.0,0.0,0.0,...,BMX,NaN,0.0,NaN,12-04-2016,16-09-2016,Y,0.0,0.0,0.0
4,2017,Kia,Sedona SX,14.167143,0.0,0.0,18.0,18.0,0.0,0.0,...,KMX,NaN,0.0,NaN,12-04-2016,02-12-2016,N,0.0,0.0,0.0

In [3]:
fuel_economy.shape

(46186, 82)

In [4]:
fuel_economy.columns

Index(['Year', 'Manufacturer', 'Model', 'barrels08', 'barrelsA08', 'charge240',
       'city08', 'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF',
       'co2', 'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'VClass',
       'highwayCD', 'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4',
       'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'youSaveSpend', 'guzzler', 'trans_dscr',
       'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA', 'evMotor',
       'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr', 'createdOn',
       'modifiedOn', 'startStop', 'phevCity', 'phevHwy', 'phevComb'],
      dtype='object')

In [5]:
fuel_economy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46186 entries, 0 to 46185
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             46186 non-null  int64
 1   Manufacturer     46186 non-null  object
 2   Model            46176 non-null  object
 3   barrels08        46169 non-null  float64
 4   barrelsA08       46169 non-null  float64
 5   charge240        46169 non-null  float64
 6   city08           46169 non-null  float64
 7   city08U          46169 non-null  float64
 8   cityA08          46169 non-null  float64
 9   cityA08U         46169 non-null  float64
 10  cityCD           46169 non-null  float64
 11  cityE            46169 non-null  float64
 12  cityUF           46169 non-null  float64
 13  co2              46169 non-null  float64
 14  co2A             46169 non-null  float64
 15  co2TailpipeAGpm  46169 non-null  float64
 16  co2TailpipeGpm   46169 non-null  float64
 17  comb08           46169 non-null  float64
 18  comb08U          46169 non-null  float64
 19  combA08          46169 non-null  float64
 20  combA08U         46169 non-null  float64
 21  combE            46169 non-null  float64
 22  combinedCD       46169 non-null  float64
 23  combinedUF       46169 non-null  float64
 24  cylinders        45663 non-null  float64
 25  displ            45665 non-null  float64
 26  drive            44983 non-null  object
 27  engId            46169 non-null  float64
 28  eng_dscr         29092 non-null  object
 29  feScore          44953 non-null  float64
 30  fuelCost08       44953 non-null  float64
 31  fuelCostA08      44953 non-null  float64
 32  fuelType         44953 non-null  object
 33  fuelType1        44953 non-null  object
 34  ghgScore         44953 non-null  float64
 35  ghgScoreA        44953 non-null  float64
 36  highway08        44953 non-null  float64
 37  highway08U       44953 non-null  float64
 38  highwayA08       44953 non-null  float64
 39  highwayA08U      44953 non-null  float64
 40  VClass           44953 non-null  object
 41  highwayCD        44192 non-null  float64
 42  highwayE         44192 non-null  float64
 43  highwayUF        44192 non-null  float64
 44  hlv              44192 non-null  float64
 45  hpv              44192 non-null  float64
 46  id               44192 non-null  float64
 47  lv2              44192 non-null  float64
 48  lv4              44192 non-null  float64
 49  mpgData          44179 non-null  object
 50  phevBlended      44192 non-null  object
 51  pv2              44192 non-null  float64
 52  pv4              44192 non-null  float64
 53  range            44192 non-null  float64
 54  rangeCity        44192 non-null  float64
 55  rangeCityA       44192 non-null  float64
 56  rangeHwy         44192 non-null  float64
 57  rangeHwyA        44192 non-null  float64
 58  trany            44181 non-null  object
 59  UCity            44192 non-null  float64
 60  UCityA           44192 non-null  float64
 61  UHighway         44192 non-null  float64
 62  UHighwayA        44192 non-null  float64
 63  youSaveSpend     44192 non-null  float64
 64  guzzler          2635 non-null   object
 65  trans_dscr       14391 non-null  object
 66  tCharger         8531 non-null   object
 67  sCharger         987 non-null    object
 68  atvType          4386 non-null   object
 69  fuelType2        1647 non-null   object
 70  rangeA           1642 non-null   object
 71  evMotor          1874 non-null   object
 72  mfrCode          15200 non-null  object
 73  c240Dscr         133 non-null    object
 74  charge240b       44170 non-null  float64
 75  c240bDscr        127 non-null    object
 76  createdOn        44170 non-null  object
 77  modifiedOn       44170 non-null  object
 78  startStop        14357 non-null  object
 79  phevCity         44170 non-null  float64
 80  phevHwy          44170 non-null  float64
 81  phevComb         44170 non-null  float64
dtypes: float64(57), int64(1), object(24)
memory usage: 28.9+ MB

Son muchas columnas para analizar, entonces nos focalizaremos en unas pocas.

A continuaciÃ³n, se analizarÃ¡ cuÃ¡les son los columnas mÃ¡s relevantes.

1. En primer lugar hay que conocer quÃ© datos tiene cada columna. Con este objetivo, se investigÃ³ en la web las siglas utilizadas en el nombre de las columnas, asÃ­ como tambiÃ©n dataset similares.

El resultado fue el siguiente:

Year: Entero (int64) - Representa el aÃ±o.

Manufacturer: Cadena de caracteres (object) - Nombre del fabricante del vehÃ­culo.

Model: Cadena de caracteres (object) - Modelo del vehÃ­culo.

barrels08: Flotante (float64) - Consumo de barriles de combustible por aÃ±o para conducciÃ³n en ciudad.

barrelsA08: Flotante (float64) - Consumo de barriles de combustible por aÃ±o alternativo para conducciÃ³n en ciudad.

charge240: Flotante (float64) - Tiempo de carga 240V.

city08: Flotante (float64) - Millas por galÃ³n (mpg) para conducciÃ³n en ciudad.

city08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) para conducciÃ³n en ciudad.

cityA08: Flotante (float64) - Millas por galÃ³n (mpg) alternativas para conducciÃ³n en ciudad.

cityA08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) alternativo para conducciÃ³n en ciudad.

cityCD: Flotante (float64) - Consumo de gasolina equivalente (GGE) para conducciÃ³n en ciudad (diesel).

cityE: Flotante (float64) - Consumo elÃ©ctrico en ciudad (Kwh/100mi).

cityUF: Flotante (float64) - Factor de utilidad de combustible para conducciÃ³n en ciudad.

co2: Flotante (float64) - Emisiones de CO2 en gramos por milla para conducciÃ³n combinada.

co2A: Flotante (float64) - Emisiones de CO2 en gramos por milla alternativas para conducciÃ³n combinada.

co2TailpipeAGpm: Flotante (float64) - Emisiones de CO2 de la cola del tubo de escape alternativas (gpm).

co2TailpipeGpm: Flotante (float64) - Emisiones de CO2 de la cola del tubo de escape (gpm).

comb08: Flotante (float64) - Millas por galÃ³n (mpg) combinadas.

comb08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) combinado.

combA08: Flotante (float64) - Millas por galÃ³n (mpg) alternativas combinadas.

combA08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) alternativo combinado.

combE: Flotante (float64) - Consumo elÃ©ctrico combinado (Kwh/100mi).

combinedCD: Flotante (float64) - Consumo de gasolina equivalente (GGE) combinado (diesel).

combinedUF: Flotante (float64) - Factor de utilidad de combustible combinado.

cylinders: Flotante (float64) - NÃºmero de cilindros del motor.

displ: Flotante (float64) - Desplazamiento del motor en litros.

drive: Cadena de caracteres (object) - Tipo de tracciÃ³n (por ejemplo, tracciÃ³n delantera, trasera, etc.).

engId: Flotante (float64) - ID del motor.

eng_dscr: Cadena de caracteres (object) - DescripciÃ³n del motor.

feScore: Flotante (float64) - PuntuaciÃ³n de eficiencia de combustible.

fuelCost08: Flotante (float64) - Costo estimado de combustible en dÃ³lares para conducciÃ³n en ciudad.

fuelCostA08: Flotante (float64) - Costo estimado de combustible en dÃ³lares alternativo para conducciÃ³n en ciudad.

fuelType: Cadena de caracteres (object) - Tipo de combustible principal.

fuelType1: Cadena de caracteres (object) - Tipo de combustible adicional.

ghgScore: Flotante (float64) - PuntuaciÃ³n de emisiones de gases de efecto invernadero.

ghgScoreA: Flotante (float64) - PuntuaciÃ³n alternativa de emisiones de gases de efecto invernadero.

highway08: Flotante (float64) - Millas por galÃ³n (mpg) para conducciÃ³n en carretera.

highway08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) para conducciÃ³n en carretera.

highwayA08: Flotante (float64) - Millas por galÃ³n (mpg) alternativas para conducciÃ³n en carretera.

highwayA08U: Flotante (float64) - Consumo de gasolina equivalente (GGE) alternativo para conducciÃ³n en carretera.

VClass: Cadena de caracteres (object) - Clase de vehÃ­culo.

highwayCD: Flotante (float64) - Consumo de gasolina equivalente (GGE) para conducciÃ³n en carretera (diesel).

highwayE: Flotante (float64) - Consumo elÃ©ctrico en carretera (Kwh/100mi).

highwayUF: Flotante (float64) - Factor de utilidad de combustible para conducciÃ³n en carretera.

hlv: Flotante (float64) - Capacidad de carga de vehÃ­culos hÃ­bridos (galones).

hpv: Flotante (float64) - Potencia hÃ­brida (HP).

id: Flotante (float64) - ID del vehÃ­culo.

lv2: Flotante (float64) - Capacidad de carga de vehÃ­culos hÃ­bridos en la segunda etapa (galones).

lv4: Flotante (float64) - Capacidad de carga de vehÃ­culos hÃ­bridos en la cuarta etapa (galones).

mpgData: Cadena de caracteres (object) - Datos de consumo de combustible (por ejemplo, "Y" para sÃ­, "N" para no).

phevBlended: Cadena de caracteres (object) - Tipo de vehÃ­culo hÃ­brido.

pv2: Flotante (float64) - Potencia del vehÃ­culo hÃ­brido en la segunda etapa (HP).

Teniendo en cuenta que el alcance del proyecto incluye aspectos relacionados con contaminaciÃ³n ambiental y que se podrÃ­an analizar cuestiones relacionadas con costos, es que se decide trabajar con un dataframe reducido:

In [6]:
#fuel_economy_reducido = fuel_economy[['id', 'Year', 'Manufacturer','Model', 'co2TailpipeGpm', 'city08', 'highway08', 'combinedUF', 'cylinders', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelType1', 'ghgScore', 'VClass']]
fuel_economy_reducido = fuel_economy[['Year', 'Manufacturer','Model', 'co2TailpipeGpm', 'city08', 'highway08', 'fuelType1','ghgScore', 'VClass', 'drive', 'fuelCost08', 'fuelCostA08']]
fuel_economy_reducido.head()

,Year,Manufacturer,Model,co2TailpipeGpm,city08,highway08,fuelType1,ghgScore,VClass,drive,fuelCost08,fuelCostA08
0,2017,BMW,M6 Coupe,519.0,15.0,22.0,Premium Gasoline,3.0,Subcompact Cars,Rear-Wheel Drive,3850.0,0.0
1,2017,BMW,X3 sDrive28i,374.0,21.0,28.0,Premium Gasoline,5.0,Small Sport Utility Vehicle 2WD,Rear-Wheel Drive,2700.0,0.0
2,2016,Infiniti,Q50S Red Sport,402.0,20.0,26.0,Premium Gasoline,5.0,Midsize Cars,Rear-Wheel Drive,2950.0,0.0
3,2017,MINI,John Cooper Works Convertible,327.0,24.0,32.0,Premium Gasoline,6.0,Minicompact Cars,Front-Wheel Drive,2400.0,0.0
4,2017,Kia,Sedona SX,433.0,18.0,25.0,Regular Gasoline,4.0,Minivan - 2WD,Front-Wheel Drive,2550.0,0.0

In [7]:
fuel_economy_reducido.shape

(46186, 12)

In [8]:
fuel_economy_reducido.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46186 entries, 0 to 46185
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            46186 non-null  int64
 1   Manufacturer    46186 non-null  object
 2   Model           46176 non-null  object
 3   co2TailpipeGpm  46169 non-null  float64
 4   city08          46169 non-null  float64
 5   highway08       44953 non-null  float64
 6   fuelType1       44953 non-null  object
 7   ghgScore        44953 non-null  float64
 8   VClass          44953 non-null  object
 9   drive           44983 non-null  object
 10  fuelCost08      44953 non-null  float64
 11  fuelCostA08     44953 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 4.2+ MB

In [9]:
fuel_economy_reducido.isnull().sum()

Year                 0
Manufacturer         0
Model               10
co2TailpipeGpm      17
city08              17
highway08         1233
fuelType1         1233
ghgScore          1233
VClass            1233
drive             1203
fuelCost08        1233
fuelCostA08       1233
dtype: int64

Dado que saber el modelo del vehÃ­culo es crucial para el anÃ¡lisis, las filas que no tienen este datos, no serÃ¡n tenidas en cuenta.

De la misma forma, tampoco serÃ¡n tenidas en cuenta las filas que no tengan datos de co2TailpipeGpm (emisiÃ³n de CO2 medida en el caÃ±o de escape en gramos por milla)

In [10]:
fuel_economy_reducido.dropna(subset=['Model', 'co2TailpipeGpm'], inplace=True)
fuel_economy_reducido.isnull().sum()

C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\100886644.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido.dropna(subset=['Model', 'co2TailpipeGpm'], inplace=True)

Year                 0
Manufacturer         0
Model                0
co2TailpipeGpm       0
city08               0
highway08         1216
fuelType1         1216
ghgScore          1216
VClass            1216
drive             1186
fuelCost08        1216
fuelCostA08       1216
dtype: int64

In [11]:
fuel_economy_reducido.describe()

,Year,co2TailpipeGpm,city08,highway08,ghgScore,fuelCost08,fuelCostA08
count,46169.000000,46169.000000,46169.000000,44953.00000,44953.000000,44953.000000,44953.000000
mean,2003.731248,457.010711,19.167493,25.24926,0.909617,2937.273374,114.070251
std,12.251662,128.683468,10.448985,9.58994,3.024930,850.006008,610.761565
min,1984.000000,0.000000,6.000000,9.00000,-1.000000,500.000000,0.000000
25%,1992.000000,380.000000,15.000000,20.00000,-1.000000,2400.000000,0.000000
50%,2005.000000,444.350000,18.000000,24.00000,-1.000000,2850.000000,0.000000
75%,2015.000000,522.764706,21.000000,28.00000,4.000000,3450.000000,0.000000
max,2024.000000,1269.571429,153.000000,140.00000,10.000000,9350.000000,5000.000000

RevisiÃ³n de valores en columnas de texto

1. Tipo de vehÃ­culo

In [12]:
sorted(fuel_economy_reducido['VClass'].astype(str).unique())

['Compact Cars',
 'Large Cars',
 'Midsize Cars',
 'Midsize Station Wagons',
 'Midsize-Large Station Wagons',
 'Minicompact Cars',
 'Minivan - 2WD',
 'Minivan - 4WD',
 'Small Pickup Trucks',
 'Small Pickup Trucks 2WD',
 'Small Pickup Trucks 4WD',
 'Small Sport Utility Vehicle 2WD',
 'Small Sport Utility Vehicle 4WD',
 'Small Station Wagons',
 'Special Purpose Vehicle 2WD',
 'Special Purpose Vehicle 4WD',
 'Special Purpose Vehicles',
 'Special Purpose Vehicles/2wd',
 'Special Purpose Vehicles/4wd',
 'Sport Utility Vehicle - 2WD',
 'Sport Utility Vehicle - 4WD',
 'Standard Pickup Trucks',
 'Standard Pickup Trucks 2WD',
 'Standard Pickup Trucks 4WD',
 'Standard Pickup Trucks/2wd',
 'Standard Sport Utility Vehicle 2WD',
 'Standard Sport Utility Vehicle 4WD',
 'Subcompact Cars',
 'Two Seaters',
 'Vans',
 'Vans Passenger',
 'nan']

Para simplificar:

Minivan - 2WD y Minivan - 4WD => Minivan

Small Pickup Trucks 2WD y Small Pickup Trucks 4WD => Small Pickup Trucks

Standard Pickup Trucks 2WD, Standard Pickup Trucks 4WD, Standard Pickup Trucks/2wd => Standard Pickup Trucks

Small Sport Utility Vehicle 2WD y Small Sport Utility Vehicle 4WD  => Small Sport Utility Vehicle

Standard Sport Utility Vehicle 2WD y Standard Sport Utility Vehicle 2WD => Standard Sport Utility Vehicle

Sport Utility Vehicle - 2WD y Sport Utility Vehicle - 4WD => Sport Utility Vehicle

Special Purpose Vehicle 2WD, Special Purpose Vehicles/2wd, Special Purpose Vehicle 4WD y Special Purpose Vehicles/4wd =>  Special Purpose Vehicle

In [13]:
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Minivan' if x== 'Minivan - 2WD' or  x == 'Minivan - 4WD' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Small Pickup Trucks' if x== 'Small Pickup Trucks 2WD' or  x == 'Small Pickup Trucks 2WD' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Standard Pickup Trucks' if x== 'Standard Pickup Trucks 2WD' or  x == 'Standard Pickup Trucks 4WD' or x == 'Standard Pickup Trucks/2wd' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Small Sport Utility Vehicle' if x== 'Small Sport Utility Vehicle 2WD' or  x == 'Small Sport Utility Vehicle 4WD' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Standard Sport Utility Vehicle' if x== 'Standard Sport Utility Vehicle 2WD' or  x == 'Standard Sport Utility Vehicle 4WD' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Sport Utility Vehicle' if x== 'Sport Utility Vehicle - 2WD' or  x == 'Sport Utility Vehicle - 4WD' else x )
fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Special Purpose Vehicle' if x== 'Special Purpose Vehicle 2WD' or  x == 'Special Purpose Vehicle 4WD' or x== 'Special Purpose Vehicles/2wd' or x == 'Special Purpose Vehicles/4wd' else x )

C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Minivan' if x== 'Minivan - 2WD' or  x == 'Minivan - 4WD' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Small Pickup Trucks' if x== 'Small Pickup Trucks 2WD' or  x == 'Small Pickup Trucks 2WD' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Standard Pickup Trucks' if x== 'Standard Pickup Trucks 2WD' or  x == 'Standard Pickup Trucks 4WD' or x == 'Standard Pickup Trucks/2wd' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Small Sport Utility Vehicle' if x== 'Small Sport Utility Vehicle 2WD' or  x == 'Small Sport Utility Vehicle 4WD' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Standard Sport Utility Vehicle' if x== 'Standard Sport Utility Vehicle 2WD' or  x == 'Standard Sport Utility Vehicle 4WD' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Sport Utility Vehicle' if x== 'Sport Utility Vehicle - 2WD' or  x == 'Sport Utility Vehicle - 4WD' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\1379391909.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['VClass'] = fuel_economy_reducido['VClass'].apply(lambda x : 'Special Purpose Vehicle' if x== 'Special Purpose Vehicle 2WD' or  x == 'Special Purpose Vehicle 4WD' or x== 'Special Purpose Vehicles/2wd' or x == 'Special Purpose Vehicles/4wd' else x )

2. Fuel Type

In [14]:
sorted(fuel_economy_reducido['fuelType1'].astype(str).unique())

['Diesel',
 'Electricity',
 'Midgrade Gasoline',
 'Natural Gas',
 'Premium Gasoline',
 'Regular Gasoline',
 'nan']

3. drive

In [15]:
sorted(fuel_economy_reducido['drive'].astype(str).unique())

['2-Wheel Drive',
 '4-Wheel Drive',
 '4-Wheel or All-Wheel Drive',
 'All-Wheel Drive',
 'Front-Wheel Drive',
 'Part-time 4-Wheel Drive',
 'Rear-Wheel Drive',
 'nan']

'4-Wheel or All-Wheel Drive', 'All-Wheel Drive' => '4-Wheel Drive'

'Rear-Wheel Drive', 'Front-Wheel Drive' => '2-Wheel Drive'

In [16]:
fuel_economy_reducido['drive'] = fuel_economy_reducido['drive'].apply(lambda x : '4-Wheel Drive' if x== '4-Wheel or All-Wheel Drive' or  x == 'All-Wheel Drive' else x )
fuel_economy_reducido['drive'] = fuel_economy_reducido['drive'].apply(lambda x : '2-Wheel Drive' if x== 'Rear-Wheel Drive' or  x == 'Front-Wheel Drive' else x )

C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\3915337598.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['drive'] = fuel_economy_reducido['drive'].apply(lambda x : '4-Wheel Drive' if x== '4-Wheel or All-Wheel Drive' or  x == 'All-Wheel Drive' else x )
C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\3915337598.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido['drive'] = fuel_economy_reducido['drive'].apply(lambda x : '2-Wheel Drive' if x== 'Rear-Wheel Drive' or  x == 'Front-Wheel Drive' else x )

In [17]:
sorted(fuel_economy_reducido['drive'].astype(str).unique())

['2-Wheel Drive', '4-Wheel Drive', 'Part-time 4-Wheel Drive', 'nan']

In [18]:
fuel_economy_reducido.isna().sum()

Year                 0
Manufacturer         0
Model                0
co2TailpipeGpm       0
city08               0
highway08         1216
fuelType1         1216
ghgScore          1216
VClass            1216
drive             1186
fuelCost08        1216
fuelCostA08       1216
dtype: int64

Finalmente, eliminamos los duplicados segÃºn marca, modelo y tipo de combustible para evitar duplicados

In [19]:
fuel_economy_reducido.drop_duplicates(subset=['Model', 'Year', 'Manufacturer', 'fuelType1', 'VClass', 'drive'], inplace=True)

C:\Users\Windows\AppData\Local\Temp\ipykernel_9716\2577049301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_economy_reducido.drop_duplicates(subset=['Model', 'Year', 'Manufacturer', 'fuelType1', 'VClass', 'drive'], inplace=True)

In [20]:
fuel_economy_reducido.shape

(25201, 12)

In [21]:
fuel_economy_reducido.isna().sum()

Year                0
Manufacturer        0
Model               0
co2TailpipeGpm      0
city08              0
highway08         718
fuelType1         718
ghgScore          718
VClass            718
drive             309
fuelCost08        718
fuelCostA08       718
dtype: int64

In [22]:
#Dataframe Final

fuel_economy_reducido

,Year,Manufacturer,Model,co2TailpipeGpm,city08,highway08,fuelType1,ghgScore,VClass,drive,fuelCost08,fuelCostA08
0,2017,BMW,M6 Coupe,519.000000,15.0,22.0,Premium Gasoline,3.0,Subcompact Cars,2-Wheel Drive,3850.0,0.0
1,2017,BMW,X3 sDrive28i,374.000000,21.0,28.0,Premium Gasoline,5.0,Small Sport Utility Vehicle,2-Wheel Drive,2700.0,0.0
2,2016,Infiniti,Q50S Red Sport,402.000000,20.0,26.0,Premium Gasoline,5.0,Midsize Cars,2-Wheel Drive,2950.0,0.0
3,2017,MINI,John Cooper Works Convertible,327.000000,24.0,32.0,Premium Gasoline,6.0,Minicompact Cars,2-Wheel Drive,2400.0,0.0
4,2017,Kia,Sedona SX,433.000000,18.0,25.0,Regular Gasoline,4.0,Minivan,2-Wheel Drive,2550.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
46148,1993,Jaguar,XJRS Coupe,740.583333,11.0,15.0,Premium Gasoline,-1.0,Subcompact Cars,2-Wheel Drive,5450.0,0.0
46149,1985,Toyota,Cargo Van 2WD,444.350000,19.0,22.0,Regular Gasoline,-1.0,Vans,2-Wheel Drive,2650.0,0.0
46166,1993,BMW,525i,467.736842,16.0,23.0,Premium Gasoline,-1.0,Compact Cars,2-Wheel Drive,3450.0,0.0
46176,1993,Mercedes-Benz,400E,493.722222,16.0,22.0,Premium Gasoline,-1.0,Compact Cars,2-Wheel Drive,3650.0,0.0
46177,1993,Mitsubishi,Diamante,493.722222,16.0,22.0,Premium Gasoline,-1.0,Compact Cars,2-Wheel Drive,3650.0,0.0

In [23]:
fuel_economy_reducido.to_csv('./Datasets_clean/Vehicle Fuel Economy Data.csv', index=False)